config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'commission/index'

  get 'commission/employee'
  devise_for :users
  resources :records
  resources :inventaries
  resources :services
  resources :clients

  resources :users, :except => [:show, :create, :update]
  



  authenticated :user do
    root 'dashboard#main'
  end
  
  unauthenticated :user do
    root 'welcome#index'
  end
  

  get 'usuarios' => 'users#index'
  get 'nuevo' => 'users#nuevo'
  get 'users/index'
  get 'commission/pagar'
  get 'inventaries/excel'
  get 'clients/buscar'
  get 'commission/index'
  get 'commission/employee'
  get 'dashboard/main'
  get 'dashboard/main'
  get 'worker/index'
  get 'commission/index'
  post 'record/create'
 

end

app/models/service.rb
class Service < ApplicationRecord
	has_many :records , dependent: :destroy
	validates :nombre,uniqueness: true
	 validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}, length: {minimum: 2, maximum: 150, :message => "El nombre debe tener entre 2 y 50 caracteres"}
  #validates :nombre, length: { in: 3..20 } no se necesita, ya esta validado el largo
  validates :nombre, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  
  #validates :precio, :numericality => { :greater_than_or_equal_to => 0 }
  #se supone que es para los numeros positivos si funciona se elimina la de arriba 
  #y se deja la de abajo y se reemplaza todas las que sean numericas y si no queda la de arriba
  validates :valor, numericality: { :greater_than_or_equal_to => 0, message: "no se permiten números negativos"}
  validates :valor, numericality: {only_integer: true, message: "solo se permiten números enteros"}
  validates :valor, length: { in: 4..7, message: "el valor debe tener entre 4 y 7 caracteres"}
  
  def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      where(nil)
    end
 end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :validar
  $titulo = 'Servicios'
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Servicio Creado.' }
        
      else
        format.html { render :new }
        
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Servicio Editado' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Servicio Eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:nombre, :valor, :estado)
    end

    def validar
      if (current_user.admin or current_user.caja or current_user.estilista)
        
        else
          redirect_to root_path
      end
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for (service), :html =>{:class => 'form-horizontal'} do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <div class="form-group">
        <%= f.label :nombre,class: 'col-sm-1 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :nombre,class:'form-control',placeholder: 'Ingrese Nombre Servicio' %>
        </div>
      </div>
  </div>

  <div class="field">
     <div class="form-group">
        <%= f.label :valor,class: 'col-sm-1 control-label' %>
        <div class="col-sm-5">
          <%= f.number_field :valor,class:'form-control' %>
        </div>
      </div>
  </div>
  <div class="actions">
    <%= f.submit('Enviar',class: 'btn btn-default') %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editar Servicio</h1>

<%= render 'form', service: @service %>

<h3><%= link_to 'Volver', services_path %></h3>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

   <% if (current_user.estilista or current_user.caja) %>
  <%else%>
  <div class="">
  <label>Crear Servicio:</label>
    <%= link_to 'Nuevo Servicio', new_service_path %>
  </div>
   <%end%>
  <div class="col-md-12">
  <h2>Busqueda Servicios</h2>
   
<%= form_tag services_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: 'Nombre de Servicio' %>
    <%= submit_tag "Buscar", :nombre => nil %>
  </p>
<% end %>

  </div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Valor</th>
      <% if (current_user.estilista or current_user.caja) %>
      <%else%>
      <th>Editar</th>
      <th>Borrar</th>
      <%end%>
      </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.nombre %></td>
        <td><%= service.valor %></td>
        <% if (current_user.estilista or current_user.caja) %>
        <%else%>
        <td><%= link_to 'Editar', edit_service_path(service) %></td>
        <td><%= link_to 'Borrar', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @services %>

<br>

app/views/services/new.html.erb
<h1>Agregar Service</h1>
<div class="col-md-12">
<%= render 'form', service: @service %>
<h3><%= link_to 'Volver', services_path %></h3>
</div>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @service.nombre %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @service.valor %>
</p>

<h3><%= link_to 'Editar', edit_service_path(@service) %></h3>
<h3><%= link_to 'Volver', services_path %></h3>