config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'commission/index'

  get 'commission/employee'
  devise_for :users
  resources :records
  resources :inventaries
  resources :services
  resources :clients

  resources :users, :except => [:show, :create, :update]
  



  authenticated :user do
    root 'dashboard#main'
  end
  
  unauthenticated :user do
    root 'welcome#index'
  end
  

  get 'usuarios' => 'users#index'
  get 'nuevo' => 'users#nuevo'
  get 'users/index'
  get 'commission/pagar'
  get 'inventaries/excel'
  get 'clients/buscar'
  get 'commission/index'
  get 'commission/employee'
  get 'dashboard/main'
  get 'dashboard/main'
  get 'worker/index'
  get 'commission/index'
  post 'record/create'
 

end

app/controllers/commission_controller.rb
class CommissionController < ApplicationController
  before_action :authenticate_user!
  before_action :validar
  $titulo = 'Comisiones' 

  def index
  	@users = User.all.order('estado DESC').where( :contador => false,:admin => false, :caja => false)
  
  end

  def employee
  	@total = 0
    if (params[:user_id] == nil)
      session[:user_id] = session[:user_id] 
    else
      session[:user_id] = params[:user_id] 
    end
  	@records = Record.where(:user_id =>session[:user_id] , :pagado => true)
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def pagar
    @record = Record.where( :user_id  => params[:user_id]).update_all( pagado: false)
    redirect_to inventaries_path
    #tb actualizar all comisiones, obtener por usuario y por all
  end
  
  private
   def record_params
      params.require(:record).permit(:pagado, :estado)
    end
    
    def validar
      if (current_user.admin or current_user.caja or current_user.contador)
        
        else
          redirect_to root_path 
        end
    end
end

app/helpers/commission_helper.rb
module CommissionHelper
end

app/views/commission/employee.html.erb
<table class="table">
<thead>
  <th>Estilista</th>
  <th>Servicio</th>
  <th>Fecha</th>
  <th>Valor</th>
  <th>Comision</th>
  <th>Total Acumulado</th>
</thead>
<tbody>
    <% @records.each do |record| %>
    <tr>
      <td><%=record.user.nombre %></td>
      <td><%=record.service.nombre %></td>
      <td><%=record.created_at %></td>
      <td><%=record.valor %></td>
      <td><%=record.comision %></td>
      <td><%= @total = @total + record.comision  %></td>
    </tr>
  <% end %>
</tbody>
</table>

<h3><%= link_to 'Exportar a Excel', commission_employee_path( format: :xlsx) %></h3>

<!--<h3><#%= link_to 'Pagar', commission_pagar_path(user_id: params[:user_id]) %></h3>
-->

<h3><%= link_to 'Volver', commission_index_path %></h3>
</div>

app/views/commission/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comisiones por Estilista</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Estilista</th>
      <th>Apellido</th>
      <th>Revisar</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if (user.estado == false) %>
      <tr style="background-color: #EDB2B2">
        <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= link_to 'Revisar', commission_employee_path(user_id:user.id) %></td>
        </tr>
        <%end%>
       <% if (user.estado == true) %>
       <tr >
         <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= link_to 'Revisar', commission_employee_path(user_id:user.id) %></td>
        </tr>
        <%end%>
      
    <% end %>
  </tbody>
</table>