config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'commission/index'

  get 'commission/employee'
  devise_for :users
  resources :records
  resources :inventaries
  resources :services
  resources :clients

  resources :users, :except => [:show, :create, :update]
  



  authenticated :user do
    root 'dashboard#main'
  end
  
  unauthenticated :user do
    root 'welcome#index'
  end
  

  get 'usuarios' => 'users#index'
  get 'nuevo' => 'users#nuevo'
  get 'users/index'
  get 'commission/pagar'
  get 'inventaries/excel'
  get 'clients/buscar'
  get 'commission/index'
  get 'commission/employee'
  get 'dashboard/main'
  get 'dashboard/main'
  get 'worker/index'
  get 'commission/index'
  post 'record/create'
 

end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :client
  belongs_to :service
  belongs_to :user
  before_save :insert
  validates :service_id , presence: true
  validates :user_id , presence: true
  validates :client_id , presence: true

	def insert
		self.valor = Service.find(self.service_id).valor
		self.comision = self.valor*0.3
		
	end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :validar
  before_action :set_record, only: [:show, :edit, :update, :destroy]


  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show

  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
 if current_user.estilista?
      redirect_to clients_path
    end
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    
    #raise params.to_yaml
    respond_to do |format|
      if @record.save
        format.html { redirect_to clients_path, notice: 'Historial Creado.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    if current_user.estilista?
      redirect_to clients_path
    else
      respond_to do |format|
        if @record.update(record_params)
          format.html { redirect_to clients_path, notice: 'Historial Actualizado.' }
          format.json { render :show, status: :ok, location: @record }
        else
          format.html { render :edit }
          format.json { render json: @record.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy

    if current_user.estilista?
      redirect_to clients_path
    else
    @record.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Registro Eliminado.' }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit( :client_id , :service_id, :user_id, :anotacion, :valor, :comision, :boleta, :fecha, :medio_pago,valor: :service_id)
    end
    def validar
      if (current_user.contador?)
        redirect_to root_path
      end
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(record) do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field(:client_id, :value => params[:id]) %>
  
  <div class="field">
     <div class="form-group">
        <%= f.label :Servicio,class: 'col-sm-1 control-label' %>
        <div class="col-sm-5">
          <%= f.select(:service_id ,Service.all.collect{ |p| [ p.nombre, p.id ] }, {prompt: false}, {class:'form-control'}) %>
        </div>
      </div>
  </div>
  <br>
  <div class="field">
     <div class="form-group">
        <%= f.label :Estilista,class: 'col-sm-1 control-label' %>
        <div class="col-sm-5">
          <%= f.select :user_id, User.where(:contador => false , :admin => false, :caja => false, :estado => true).collect{ |p| [ p.nombre + ' ' + p.apellido, p.id ] }, {prompt: false}, {class:'form-control'} %>
        </div>
      </div>
  </div>
  <br>
  <div class="field">
     <div class="form-group">
        <%= f.label :anotacion,class: 'col-sm-1 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :anotacion,class:'form-control',placeholder: 'Ingrese Anotacion Pertinente' %>
        </div>
      </div>
  </div>
  <br>
  
  <br>
 
  <br><br><br>
 
  <div class="actions">
    <%= f.submit('Guardar',class: 'btn btn-default') %>
  </div>
<% end %>



 
  
 

  

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<h3><%= link_to 'Volver', clients_path %></h3>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Clients</th>
      <th>Service</th>
      <th>Users</th>
      <th>Anotacion</th>
      <th>Valor</th>
      <th>Comision</th>
      <th>Boleta</th>
      <th>Fecha</th>
      <th>Medio pago</th>
      <th>Activo</th>
      <th>Estado</th>
      <th>Pagado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.client.id %></td>
        <td><%= record.service.id %></td>
        <td><%= record.user.id %></td>
        <td><%= record.anotacion %></td>
        <td><%= record.valor %></td>
        <td><%= record.comision %></td>
        <td><%= record.boleta %></td>
        <td><%= record.fecha %></td>
        <td><%= record.medio_pago %></td>
        <td><%= record.activo %></td>
        <td><%= record.estado %></td>
        <td><%= record.pagado %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>Nuevo Registro</h1>

<%= render 'form', record: @record %>

<h3><%= link_to 'Volver', records_path %></h3>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clients:</strong>
  <%= @record.client.nombre %>
</p>

<p>
  <strong>Service:</strong>
  <%= @record.service.nombre %>
</p>

<p>
  <strong>Users:</strong>
  <%= @record.user.nombre %>
</p>

<p>
  <strong>Anotacion:</strong>
  <%= @record.anotacion %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @record.valor %>
</p>

<p>
  <strong>Comision:</strong>
  <%= @record.comision %>
</p>

<p>
  <strong>Boleta:</strong>
  <%= @record.boleta %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @record.fecha %>
</p>

<p>
  <strong>Medio pago:</strong>
  <%= @record.medio_pago %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @record.activo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @record.estado %>
</p>

<p>
  <strong>Pagado:</strong>
  <%= @record.pagado %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>