config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'commission/index'

  get 'commission/employee'
  devise_for :users
  resources :records
  resources :inventaries
  resources :services
  resources :clients

  resources :users, :except => [:show, :create, :update]
  



  authenticated :user do
    root 'dashboard#main'
  end
  
  unauthenticated :user do
    root 'welcome#index'
  end
  

  get 'usuarios' => 'users#index'
  get 'nuevo' => 'users#nuevo'
  get 'users/index'
  get 'commission/pagar'
  get 'inventaries/excel'
  get 'clients/buscar'
  get 'commission/index'
  get 'commission/employee'
  get 'dashboard/main'
  get 'dashboard/main'
  get 'worker/index'
  get 'commission/index'
  post 'record/create'
 

end

app/views/layouts/_menu.html.erb
            <div class="navbar-default sidebar" role="navigation" style="margin-top:100px;">
                <div class="sidebar-nav navbar-collapse" >
                    <ul class="nav" id="side-menu">
                      <% if user_signed_in? %>
                      
                        <% if (current_user.admin or current_user.caja or current_user.estilista) %>
                        <li>
                            <%= link_to clients_path do %>
                            <i class="fa fa-user fa-fw"></i>Clientes
                            <% end %>
                        </li>
                        <%end%>
                        <% if (current_user.admin or current_user.caja or current_user.estilista) %>
                        <li>
                            <%= link_to services_path do %>
                            <i class="fa fa-file fa-fw"></i>Servicios
                            <% end %>
                        </li>
                        <%end%>
                        <% if (current_user.admin or current_user.caja) %>
                         <li>
                            <%= link_to inventaries_path do %>
                            <i class="fa fa-sitemap fa-fw"></i>Productos
                            <% end %>
                        </li>
                        <%end%>
                        <% if (current_user.admin or current_user.contador or current_user.caja) %>
                        <li>
                            <%= link_to commission_index_path do %>
                            <i class="fa fa-money fa-fw"></i>Comisiones
                            <% end %>
                        </li>
                        <%end%>
                        <% if (current_user.admin) %>
                        <li>
                            <%= link_to users_index_path do %>
                            <i class="fa fa-table fa-fw"></i>Usuarios
                            <% end %>
                        </li>
                        <%end%>
                         
                       
                         
                        <% else %>
                         <li>
                            <%= link_to "Inicio Sesion",new_user_session_path%>
            
                        </li>
                       
                        
                         <% end %>

                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sys-Venus</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="app/assets/stylesheets/layout.scss">
  </head>

 <body>
    

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" style="margin-bottom: 0; height: 100px">
                <%= image_tag "logo.jpg", :style => "height: 100%; width: 100%;" %>
                <%= link_to 'Peluqueria Venus', root_path , class: 'navbar-brand' %></a>
           </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <% if user_signed_in?%>
                        <i class="fa fa-user fa-fw"></i>Usuario: <%= current_user.nombre + ' ' +  current_user.apellido%></i><i class="fa fa-caret-down"></i>
                        
                        
                        <br>
                     <%if (current_user.admin) %>
                        <p>Permiso: Admin </p>
                    <% end%> 
                    <%if (current_user.caja) %>
                        <p>Permiso: Caja </p>
                    <% end%> 
                    <%if (current_user.contador) %>
                        <p>Permiso: Contador </p>
                    <% end%> 
                    <%if (current_user.estilista) %>
                        <p>Permiso: Estilista</p>
                    <% end%> 
                        
                        
                        <% end %>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                    <% if user_signed_in?%>
                        <li>
                        <%= link_to "Cerrar sesión",destroy_user_session_path,method: :delete%>
                        </li>
                        <% else%>
                        <%= link_to "Inicio Sesion",new_user_session_path%>
                      
                        <% end %>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

        <%= render 'layouts/menu' %>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper" >
            <div class="row">
                <div class="col-lg-12">
                    <!--=========================NOTIFICACIONES========================-->

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<!--========================FIN NOTIFICACIONES=====================-->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

            <div class="row" >
                <div class="col-lg-12" >
                <%= yield  %>
                </div>
            </div>
      
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    
</body>

</html>